export const ROLES = {
GLOBAL_ADMIN: 'global_admin',
CHURCH_ADMIN: 'church_admin',
MINISTRY_STAFF: 'ministry_staff',
CHURCH_STAFF: 'church_staff',
ATTENDANCE_TRACKER: 'attendance_tracker',
CHURCH_MEMBER: 'church_member',
};

export const PERMISSIONS = {
view_all_dashboards: [ROLES.GLOBAL_ADMIN],
view_church_dashboard: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.ATTENDANCE_TRACKER],
manage_church_settings: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
manage_all_churches: [ROLES.GLOBAL_ADMIN],
manage_members: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
view_members: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.ATTENDANCE_TRACKER, ROLES.CHURCH_MEMBER],
take_attendance: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.ATTENDANCE_TRACKER],
manage_attendance: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
record_giving: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.CHURCH_STAFF],
view_giving: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF],
manage_giving: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
view_spiritual_records: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.CHURCH_STAFF],
manage_spiritual_records: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
manage_ministry_groups: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF],
manage_ministry_schedules: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF],
view_ministry_groups: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.ATTENDANCE_TRACKER, ROLES.CHURCH_MEMBER],
manage_bible_studies: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
view_bible_studies: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.CHURCH_MEMBER],
manage_study_guides: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
manage_livestream: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
view_livestream: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.CHURCH_MEMBER],
manage_users: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
invite_users: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
mass_texting: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
manage_follow_ups: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF],
export_data: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN],
submit_prayer_requests: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.CHURCH_MEMBER],
view_prayer_requests: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.CHURCH_MEMBER],
join_ministry_groups: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.CHURCH_MEMBER],
chat: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF],
view_directory: [ROLES.GLOBAL_ADMIN, ROLES.CHURCH_ADMIN, ROLES.MINISTRY_STAFF, ROLES.CHURCH_STAFF, ROLES.CHURCH_MEMBER],
};

export function hasPermission(userRole, permission) {
if (!userRole ||!PERMISSIONS[permission]) return false;
return PERMISSIONS[permission].includes(userRole);
}

export function isGlobalAdmin(userRole) {
return userRole === ROLES.GLOBAL_ADMIN;
}

export function isChurchAdmin(userRole) {
return userRole === ROLES.CHURCH_ADMIN;
}

export function isAdmin(userRole) {
return userRole === ROLES.GLOBAL_ADMIN || userRole === ROLES.CHURCH_ADMIN;
}